"""
[AI Agent & Automation System]
Created for: Mohit Muliyashiya
"""
import os
import sys
import time
import datetime
import subprocess
import urllib.parse
import webbrowser

# Fix Windows encoding for console output
if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

class AIAgent:
    def __init__(self, name="Jarvis"):
        self.name = name
        self.user_name = "Mohit"
        self.notes_file = "my_notes.txt"

    def greet(self):
        hour = datetime.datetime.now().hour
        if hour < 12:
            time_greet = "Good Morning"
        elif hour < 17:
            time_greet = "Good Afternoon"
        else:
            time_greet = "Good Evening"

        print("=" * 60)
        print(f"[+] Namaste {self.user_name}! {time_greet}.")
        print(f"Main hoon aapka AI Agent ({self.name}).")
        print("Aap mujhse code generate karwa sakte ho, apps open karwa sakte ho,")
        print("search karwa sakte ho ya koi bhi task perform karwa sakte ho.")
        print("=" * 60)
        print(">> Examples / Commands:")
        print("  1. 'generate code for calculator'")
        print("  2. 'generate html website'")
        print("  3. 'calculate 45 * 12 + 100'")
        print("  4. 'open chrome' ya 'open notepad'")
        print("  5. 'search python tutorial'")
        print("  6. 'run code <filename.py>'")
        print("  7. 'save note Kal exam hai'")
        print("  8. 'time' ya 'date'")
        print("  9. 'exit' to quit")
        print("=" * 60)

    # TOOL 1: Code & File Generator
    def tool_generate_code(self, prompt):
        prompt_lower = prompt.lower()
        filename = "generated_code.py"
        code = ""

        if "calculator" in prompt_lower:
            filename = "generated_calculator.py"
            code = '''# Simple Calculator generated by AI Agent
def add(a, b): return a + b
def subtract(a, b): return a - b
def multiply(a, b): return a * b
def divide(a, b): return a / b if b != 0 else "Error: Division by zero"

print("=" * 30)
print("     --- Calculator ---")
print("=" * 30)
print("1. Add (+)")
print("2. Subtract (-)")
print("3. Multiply (*)")
print("4. Divide (/)")
print("=" * 30)

choice = input("Enter choice (1-4): ")
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

if choice == '1':
    print(f"Result: {num1} + {num2} = {add(num1, num2)}")
elif choice == '2':
    print(f"Result: {num1} - {num2} = {subtract(num1, num2)}")
elif choice == '3':
    print(f"Result: {num1} * {num2} = {multiply(num1, num2)}")
elif choice == '4':
    print(f"Result: {num1} / {num2} = {divide(num1, num2)}")
else:
    print("Invalid Choice")
'''
        elif "html" in prompt_lower or "website" in prompt_lower or "portfolio" in prompt_lower:
            filename = "generated_website.html"
            code = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mohit Muliyashiya - Portfolio</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1e1e2f, #2a2b4a);
            color: #ffffff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .card {
            background: rgba(255, 255, 255, 0.08);
            backdrop-filter: blur(10px);
            padding: 40px;
            border-radius: 20px;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
            border: 1px solid rgba(255, 255, 255, 0.18);
            max-width: 500px;
            text-align: center;
        }
        h1 { color: #00d2ff; margin-bottom: 5px; }
        p { color: #cfcfcf; line-height: 1.6; }
        .skills {
            display: flex;
            gap: 10px;
            justify-content: center;
            flex-wrap: wrap;
            margin-top: 20px;
        }
        .skill-tag {
            background: #00d2ff;
            color: #000;
            padding: 6px 14px;
            border-radius: 20px;
            font-weight: bold;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="card">
        <h1>Mohit Muliyashiya</h1>
        <p>Python Developer & AI Enthusiast</p>
        <div class="skills">
            <span class="skill-tag">Python</span>
            <span class="skill-tag">AI Agent</span>
            <span class="skill-tag">Data Science</span>
            <span class="skill-tag">HTML/CSS</span>
        </div>
        <p style="margin-top: 25px;">Welcome to my official portfolio created automatically by my AI Agent!</p>
    </div>
</body>
</html>
'''
        elif "prime" in prompt_lower:
            filename = "generated_prime.py"
            code = '''# Prime Number Checker generated by AI Agent
num = int(input("Enter a number to check if Prime: "))

if num > 1:
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(f"Yes! {num} is a Prime Number.")
    else:
        print(f"No! {num} is NOT a Prime Number.")
else:
    print(f"No! {num} is NOT a Prime Number.")
'''
        elif "snake" in prompt_lower or "game" in prompt_lower:
            filename = "generated_game.py"
            code = '''# Number Guessing Game generated by AI Agent
import random

def play_game():
    secret = random.randint(1, 100)
    attempts = 0
    print("Welcome to Number Guessing Game (1 to 100)!")
    
    while True:
        try:
            guess = int(input("Enter your guess: "))
            attempts += 1
            if guess < secret:
                print("Too Low! Try again.")
            elif guess > secret:
                print("Too High! Try again.")
            else:
                print(f"Congratulations! You guessed the number in {attempts} attempts!")
                break
        except ValueError:
            print("Please enter a valid number.")

if __name__ == "__main__":
    play_game()
'''
        else:
            filename = "generated_script.py"
            code = f'''# Generated script for: {prompt}
print("Executing custom task: {prompt}")

def main():
    print("Hello from AI Agent generated code!")
    for i in range(1, 6):
        print(f"Step {{i}}: Processing {prompt}...")
    print("Task completed successfully!")

if __name__ == "__main__":
    main()
'''

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)

        print(f"\n[OK] [Tool: Code Generator] File successfully generated: {filename}")
        print("-" * 50)
        print(code)
        print("-" * 50)
        return filename

    # TOOL 2: Calculator & Math Tool
    def tool_calculator(self, expr):
        try:
            clean_expr = expr.replace("calculate", "").replace("calc", "").replace("math", "").strip()
            allowed_chars = "0123456789+-*/().% "
            if all(c in allowed_chars for c in clean_expr):
                result = eval(clean_expr)
                print(f"[=] [Tool: Calculator] Result: {clean_expr} = {result}")
                return result
            else:
                print("[!] [Tool: Calculator] Sirf mathematical expressions (+, -, *, /, %) allow hain.")
        except Exception as e:
            print(f"[X] Calculation error: {e}")

    # TOOL 3: System / App Launcher Tool
    def tool_open_app(self, query):
        q = query.lower()
        print(f"[*] [Tool: App Opener] Opening requested application...")
        if "chrome" in q or "browser" in q or "google" in q:
            webbrowser.open("https://www.google.com")
            print("[+] Google Chrome opened.")
        elif "notepad" in q:
            subprocess.Popen(["notepad.exe"])
            print("[+] Notepad opened.")
        elif "calc" in q or "calculator" in q:
            subprocess.Popen(["calc.exe"])
            print("[+] Windows Calculator opened.")
        elif "cmd" in q or "terminal" in q:
            subprocess.Popen(["cmd.exe"])
            print("[+] Terminal opened.")
        elif "youtube" in q:
            webbrowser.open("https://www.youtube.com")
            print("[+] YouTube opened.")
        elif "github" in q:
            webbrowser.open("https://www.github.com")
            print("[+] GitHub opened.")
        else:
            print("[!] Application samajh nahi aayi. (Chrome, Notepad, Calc, YouTube, CMD try karein)")

    # TOOL 4: Web Search Tool
    def tool_web_search(self, query):
        search_term = query.replace("search", "").replace("find", "").replace("google", "").strip()
        url = f"https://www.google.com/search?q={urllib.parse.quote(search_term)}"
        print(f"[*] [Tool: Web Search] Searching web for: '{search_term}'...")
        webbrowser.open(url)
        print(f"[OK] Search results opened in your browser.")

    # TOOL 5: Code Runner Tool
    def tool_run_code(self, filename):
        filename = filename.strip()
        if not os.path.exists(filename):
            print(f"[X] File not found: {filename}")
            return
        print(f"[*] [Tool: Code Runner] Running {filename}...\n" + "=" * 40)
        try:
            # Run in interactive mode or separate process
            subprocess.Popen([sys.executable, filename], creationflags=subprocess.CREATE_NEW_CONSOLE)
            print(f"[OK] {filename} is now running in a new window!")
        except Exception as e:
            print(f"Execution failed: {e}")
        print("=" * 40)

    # TOOL 6: Notes & Memory Tool
    def tool_save_note(self, text):
        note = text.replace("save note", "").replace("note", "").strip()
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(self.notes_file, "a", encoding="utf-8") as f:
            f.write(f"[{timestamp}] {note}\n")
        print(f"[+] [Tool: Notes] Note saved successfully: '{note}'")

    def tool_read_notes(self):
        if not os.path.exists(self.notes_file):
            print("[!] Koi notes nahi mile.")
            return
        print("\n[Notes] Aapke Saved Notes:")
        with open(self.notes_file, "r", encoding="utf-8") as f:
            print(f.read())

    # Intent Processor / Dispatcher
    def process_command(self, user_input):
        cmd = user_input.strip()
        cmd_lower = cmd.lower()

        if not cmd:
            return

        if cmd_lower in ["exit", "quit", "bye", "band karo"]:
            print(f"[*] Alvida {self.user_name}! Have a great day!")
            return "EXIT"

        # Check for Code Generation
        elif any(k in cmd_lower for k in ["generate", "banao", "code", "create", "website", "calculator", "game", "prime"]):
            self.tool_generate_code(cmd)

        # Check for Calculator / Math
        elif any(k in cmd_lower for k in ["calculate", "calc", "math", "+", "*", "/"]) and any(c.isdigit() for c in cmd):
            self.tool_calculator(cmd)

        # Check for App Opener
        elif any(k in cmd_lower for k in ["open", "chalao", "kholo"]):
            self.tool_open_app(cmd)

        # Check for Web Search
        elif any(k in cmd_lower for k in ["search", "find", "google karo", "dhoondo"]):
            self.tool_web_search(cmd)

        # Check for Run Code
        elif cmd_lower.startswith("run code") or cmd_lower.startswith("run"):
            parts = cmd.split(" ", 2)
            fname = parts[-1] if len(parts) > 1 and parts[-1].endswith(".py") else "generated_calculator.py"
            self.tool_run_code(fname)

        # Check for Notes
        elif "save note" in cmd_lower or "note likho" in cmd_lower or "add note" in cmd_lower:
            self.tool_save_note(cmd)
        elif "read note" in cmd_lower or "show notes" in cmd_lower or "notes" == cmd_lower:
            self.tool_read_notes()

        # Date / Time
        elif "time" in cmd_lower or "samay" in cmd_lower:
            print("[Time] Current Time:", datetime.datetime.now().strftime("%I:%M:%S %p"))
        elif "date" in cmd_lower or "tarikh" in cmd_lower:
            print("[Date] Current Date:", datetime.datetime.now().strftime("%A, %d %B %Y"))

        # Who are you / Introduction
        elif "who are you" in cmd_lower or "kaun ho" in cmd_lower:
            print(f"[AI] Main aapka personal AI Agent hoon, Mohit! Aap mujhe task batao, main kar dunga.")

        else:
            print(f"[*] Processing task: '{cmd}'")
            self.tool_generate_code(cmd)

    def run(self):
        self.greet()
        while True:
            try:
                user_input = input(f"\n[Mohit] >> ")
                status = self.process_command(user_input)
                if status == "EXIT":
                    break
            except KeyboardInterrupt:
                print(f"\n[*] Bye {self.user_name}!")
                break
            except Exception as e:
                print(f"[!] Error: {e}")

if __name__ == "__main__":
    agent = AIAgent(name="Jarvis")
    agent.run()
