"""
===================================================================="n               ⚡ J.A.R.V.I.S. AI AGENT SYSTEM ⚡
        Just A Rather Very Intelligent System for Mohit
===================================================================="n"""
import os
import sys
import time
import datetime
import subprocess
import urllib.parse
import webbrowser
import threading

# Windows UTF-8 console output setup
if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

class JarvisAI:
    def __init__(self):
        self.name = "JARVIS"
        self.user_name = "Boss Mohit"
        self.notes_file = "jarvis_notes.txt"
        self.voice_enabled = True

    def speak(self, text):
        """Speaks the text using Windows Built-in SAPI Voice (Async)"""
        print(f"[JARVIS 🗣️] : {text}")
        if self.voice_enabled:
            def _speak_thread():
                try:
                    clean_text = text.replace("'", "").replace('"', '').replace('\n', ' ')
                    cmd = f"(New-Object -ComObject SAPI.SpVoice).Speak('{clean_text}')"
                    subprocess.run(
                        ["powershell", "-NoProfile", "-NonInteractive", "-Command", cmd],
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL
                    )
                except Exception:
                    pass
            threading.Thread(target=_speak_thread, daemon=True).start()

    def banner(self):
        print("""
===================================================================="n   __    _    ____  _   _ ___ ____      _    ___ 
  |  |  / \  |  _ \| | | |_ _/ ___|    / \  |_ _|
  |  | / _ \ | |_) | | | || |\___ \   / _ \  | | 
| |/ // ___ \|  _ <\ \_/ /| | ___) | / ___ \ | | 
|___//_/   \_\_| \_\\___/|___|____/ /_/   \_\___|

        >> STATUS: ONLINE | PROTOCOL: READY <<
        >> USER: MOHIT MULIYASHIYA         <<
===================================================================="n""")
        self.speak(f"Systems initialized. Welcome back, {self.user_name}. How can I help you today?")

    # 🛠️ TOOL 1: Autonomous Code Generator
    def tool_generate_code(self, prompt):
        p = prompt.lower()
        self.speak("Generating requested code...")
        filename = "jarvis_calculator.py"
        code = ""

        if "calculator" in p:
            filename = "jarvis_calculator.py"
            code = '''# Generated by JARVIS AI
def add(a, b): return a + b
def sub(a, b): return a - b
def mul(a, b): return a * b
def div(a, b): return a / b if b != 0 else "Error: Division by 0"

print("=" * 40)
print("       ⚡ JARVIS CALCULATOR ⚡")
print("=" * 40)
num1 = float(input("Enter First Number: "))
op = input("Enter Operator (+, -, *, /): ").strip()
num2 = float(input("Enter Second Number: "))

if op == '+': print(f"Result: {num1} + {num2} = {add(num1, num2)}")
elif op == '-': print(f"Result: {num1} - {num2} = {sub(num1, num2)}")
elif op == '*': print(f"Result: {num1} * {num2} = {mul(num1, num2)}")
elif op == '/': print(f"Result: {num1} / {num2} = {div(num1, num2)}")
else: print("Invalid Operator")
'''
        elif "html" in p or "website" in p or "portfolio" in p:
            filename = "jarvis_portfolio.html"
            code = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mohit Muliyashiya | AI Developer</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Segoe UI', sans-serif; }
        body { background: #0b0c10; color: #c5c6c7; min-height: 100vh; display: flex; justify-content: center; align-items: center; }
        .hud-card {
            background: rgba(31, 40, 51, 0.7);
            border: 2px solid #66fcf1;
            box-shadow: 0 0 25px rgba(102, 252, 241, 0.4);
            border-radius: 16px;
            padding: 40px;
            max-width: 600px;
            text-align: center;
        }
        h1 { color: #66fcf1; font-size: 2.2rem; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 2px; }
        h3 { color: #45a29e; margin-bottom: 20px; font-weight: 400; }
        p { font-size: 1.05rem; line-height: 1.6; margin-bottom: 25px; }
        .tags { display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; margin-bottom: 25px; }
        .tag { background: #45a29e; color: #0b0c10; padding: 6px 16px; border-radius: 20px; font-weight: bold; font-size: 0.9rem; }
        .btn {
            background: transparent;
            border: 2px solid #66fcf1;
            color: #66fcf1;
            padding: 10px 24px;
            border-radius: 8px;
            cursor: pointer;
            font-size: 1rem;
            transition: all 0.3s ease;
        }
        .btn:hover { background: #66fcf1; color: #0b0c10; box-shadow: 0 0 15px #66fcf1; }
    </style>
</head>
<body>
    <div class="hud-card">
        <h1>Mohit Muliyashiya</h1>
        <h3>Python & AI Specialist</h3>
        <div class="tags">
            <span class="tag">Python 3.14</span>
            <span class="tag">JARVIS AI</span>
            <span class="tag">Automation</span>
            <span class="tag">Machine Learning</span>
        </div>
        <p>Welcome to my command center. Engineered and automated through JARVIS AI Agent.</p>
        <button class="btn" onclick="alert('JARVIS System Connected!')">Access Core</button>
    </div>
</body>
</html>
'''
        elif "game" in p or "snake" in p or "guess" in p:
            filename = "jarvis_number_game.py"
            code = '''# Interactive Number Guessing Game
import random

def game():
    number = random.randint(1, 100)
    tries = 0
    print("=" * 40)
    print("   🎮 JARVIS NUMBER GUESS GAME 🎮")
    print("Guess a number between 1 and 100")
    print("=" * 40)
    
    while True:
        try:
            guess = int(input("Enter your guess: "))
            tries += 1
            if guess < number:
                print("🔺 Too Low! Aim higher.")
            elif guess > number:
                print("🔻 Too High! Aim lower.")
            else:
                print(f"🎯 BINGO! You won in {tries} tries!")
                break
        except ValueError:
            print("Please enter a valid number.")

if __name__ == "__main__":
    game()
'''
        elif "prime" in p:
            filename = "jarvis_prime_check.py"
            code = '''# Prime Number Detector
num = int(input("Enter integer to test for Prime: "))
if num > 1:
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(f"✅ {num} is a PRIME number.")
    else:
        print(f"❌ {num} is NOT prime (divisible by {i}).")
else:
    print(f"❌ {num} is NOT prime.")
'''
        else:
            filename = "jarvis_custom_task.py"
            code = f'''# Custom Python Script for: {prompt}
def execute_task():
    print("========================================")
    print("⚡ JARVIS Custom Task Execution")
    print("Task: {prompt}")
    print("========================================")
    for step in range(1, 6):
        print(f"[*] Processing Phase {{step}}/5...")
    print("✅ Execution Completed Successfully!")

if __name__ == "__main__":
    execute_task()
'''

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)

        print(f"\n[OK] Generated Script: {filename}")
        print("=" * 50)
        print(code)
        print("=" * 50)
        self.speak(f"Code generation complete for {filename}.")
        return filename

    # 🛠️ TOOL 2: App & System Launcher
    def tool_open_app(self, query):
        q = query.lower()
        if "chrome" in q or "browser" in q:
            self.speak("Opening Google Chrome.")
            webbrowser.open("https://www.google.com")
        elif "youtube" in q:
            self.speak("Launching YouTube.")
            webbrowser.open("https://www.youtube.com")
        elif "notepad" in q:
            self.speak("Launching Notepad.")
            subprocess.Popen(["notepad.exe"])
        elif "calc" in q or "calculator" in q:
            self.speak("Launching Calculator.")
            subprocess.Popen(["calc.exe"])
        elif "cmd" in q or "terminal" in q:
            self.speak("Opening Command Prompt.")
            subprocess.Popen(["cmd.exe"])
        elif "code" in q or "vs code" in q or "vscode" in q:
            self.speak("Opening Visual Studio Code.")
            subprocess.Popen(["code"])
        else:
            self.speak("Target application not identified. Opening browser.")
            webbrowser.open("https://www.google.com")

    # 🛠️ TOOL 3: Real-Time Web Search & Media Player
    def tool_search_web(self, query):
        q = query.replace("search", "").replace("google", "").replace("find", "").replace("play", "").strip()
        if "play" in query.lower():
            self.speak(f"Playing {q} on YouTube.")
            url = f"https://www.youtube.com/results?search_query={urllib.parse.quote(q)}"
        else:
            self.speak(f"Searching web for {q}.")
            url = f"https://www.google.com/search?q={urllib.parse.quote(q)}"
        webbrowser.open(url)

    # 🛠️ TOOL 4: Math Engine & Currency Converter
    def tool_math(self, expr):
        try:
            if "usd" in expr.lower() or "dollar" in expr.lower() or "inr" in expr.lower():
                nums = [float(s) for s in expr.split() if s.replace('.', '', 1).isdigit()]
                usd = nums[0] if nums else 1.0
                inr = usd * 96.80
                res = f"${usd} USD = {inr:.2f} INR"
                print(f"[JARVIS MATH] {res}")
                self.speak(res)
                return
            
            clean = expr.replace("calculate", "").replace("calc", "").replace("math", "").strip()
            allowed = "0123456789+-*/().% "
            if all(c in allowed for c in clean):
                val = eval(clean)
                ans = f"The answer to {clean} is {val}"
                print(f"[JARVIS MATH] {clean} = {val}")
                self.speak(ans)
        except Exception as e:
            print(f"[Error] {e}")

    # 🛠️ TOOL 5: Script Runner
    def tool_run_code(self, script_name):
        fname = script_name.strip()
        if not os.path.exists(fname):
            print(f"[!] File '{fname}' does not exist.")
            self.speak(f"File {fname} not found.")
            return
        self.speak(f"Running {fname} in a new window.")
        subprocess.Popen([sys.executable, fname], creationflags=subprocess.CREATE_NEW_CONSOLE)

    # 🛠️ TOOL 6: Memory & Notes
    def tool_notes(self, text, mode="save"):
        if mode == "save":
            note = text.replace("save note", "").replace("note", "").strip()
            timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
            with open(self.notes_file, "a", encoding="utf-8") as f:
                f.write(f"[{timestamp}] {note}\n")
            print(f"[Note Saved] {note}")
            self.speak("Note recorded to memory bank.")
        else:
            if os.path.exists(self.notes_file):
                with open(self.notes_file, "r", encoding="utf-8") as f:
                    print("\n--- 📝 JARVIS MEMORY LOGS ---")
                    print(f.read())
                self.speak("Displaying your saved notes.")
            else:
                self.speak("Memory logs are currently empty.")

    # 🧠 Central Intelligence Router
    def handle_command(self, cmd):
        c = cmd.strip()
        c_low = c.lower()
        if not c:
            return

        if c_low in ["exit", "quit", "shutdown", "bye", "band karo"]:
            self.speak(f"Shutting down core systems. Goodbye {self.user_name}!")
            return "EXIT"

        # Voice control
        elif "voice off" in c_low or "mute" in c_low:
            self.voice_enabled = False
            print("[Voice Disabled]")
        elif "voice on" in c_low or "unmute" in c_low:
            self.voice_enabled = True
            self.speak("Voice synthesizer active.")

        # Code Generation
        elif any(w in c_low for w in ["generate", "code", "banao", "create", "website", "game", "calculator", "prime"]):
            self.tool_generate_code(c)

        # App Launch
        elif any(w in c_low for w in ["open", "launch", "kholo", "chalao"]) and not c_low.startswith("run code"):
            self.tool_open_app(c)

        # Search / Play Media
        elif any(w in c_low for w in ["search", "find", "google", "play", "gana", "song"]):
            self.tool_search_web(c)

        # Math / Currency
        elif any(w in c_low for w in ["calculate", "calc", "math", "+", "*", "/", "usd", "inr"]) and any(char.isdigit() for char in c):
            self.tool_math(c)

        # Execute Script
        elif c_low.startswith("run"):
            parts = c.split(" ", 2)
            fname = parts[-1] if len(parts) > 1 and parts[-1].endswith(".py") else "generated_calculator.py"
            self.tool_run_code(fname)

        # Notes
        elif "save note" in c_low or "add note" in c_low:
            self.tool_notes(c, mode="save")
        elif "show note" in c_low or "read note" in c_low or "notes" == c_low:
            self.tool_notes(c, mode="read")

        # Time / Date / Diagnostics
        elif "time" in c_low or "samay" in c_low:
            now = datetime.datetime.now().strftime("%I:%M %p")
            print(f"[Time] {now}")
            self.speak(f"The current time is {now}")
        elif "date" in c_low or "tarikh" in c_low:
            today = datetime.datetime.now().strftime("%A, %B %d, %Y")
            print(f"[Date] {today}")
            self.speak(f"Today is {today}")

        # Who are you / status
        elif "who are you" in c_low or "status" in c_low or "kaun ho" in c_low:
            self.speak("I am JARVIS, your personal autonomous AI agent system, engineered for Mohit.")

        else:
            self.speak(f"Executing protocol for {c}")
            self.tool_generate_code(c)

    def run(self):
        self.banner()
        while True:
            try:
                user_cmd = input(f"\n[⚡ {self.user_name}] >> ")
                status = self.handle_command(user_cmd)
                if status == "EXIT":
                    break
            except KeyboardInterrupt:
                self.speak(f"Process terminated. Goodbye {self.user_name}!")
                break
            except Exception as e:
                print(f"[System Error] {e}")

if __name__ == "__main__":
    jarvis = JarvisAI()
    jarvis.run()
